apiVersion: v1
kind: Service
metadata:
  name: illusive-service
spec:
  selector:
    app: illusive
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: illusive
spec:
  selector:
    matchLabels:
      app: illusive
  replicas: 2
  template:
    metadata:
      labels:
        app: illusive
    spec:
      containers:
      - name: illusive
        image: illusive
        imagePullPolicy: Never
        ports:
        - containerPort: 5000