apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-01T14:35:52Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: illusive
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-10-01T14:35:52Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-10-01T14:36:35Z"
  name: illusive-service
  namespace: default
  resourceVersion: "494130"
  uid: 8962f3eb-cff1-4468-b9a7-57fa207cda18
spec:
  clusterIP: 10.27.248.143
  clusterIPs:
  - 10.27.248.143
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31178
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: illusive
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.122.90.77
